language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev
    - travis_retry composer dump-autoload -o
    - cd test

script: ../vendor/bin/phpunit ApplicationTest.php